project:
  type: website
  output-dir: docs

website:
  title: "LANDFIRE 101"
  sidebar: 
    style: "docked"
    search: true
    contents:
      - text: "LANDFIRE: an introduction"
        href: index.qmd
      - text: "An Overview of LANDFIRE Products"
        href: 1_what-is-landfire.qmd
      - text: "Explore LANDFIRE spatial data"
        href: 2_landfire-attributes.qmd
      - section: "LANDFIRE Vegetation Datasets"
        contents:
          - href: LANDFIRE_Datasets/1_Vegetation/1_lf-vegetation-data.qmd
          - section: "Biophysical Settings"
            contents:
              - href: LANDFIRE_Datasets/1_Vegetation/Biophysical_Settings/1-bps.qmd
              - href: LANDFIRE_Datasets/1_Vegetation/Biophysical_Settings/2-bps_spatial.qmd
              - href: LANDFIRE_Datasets/1_Vegetation/Biophysical_Settings/3-bps_documents.qmd
              - href: LANDFIRE_Datasets/1_Vegetation/Biophysical_Settings/4-bps-models.qmd
              - href: LANDFIRE_Datasets/1_Vegetation/Biophysical_Settings/5-refcon-table.qmd
          - section: "Existing Vegetation"
            contents:
              - href: LANDFIRE_Datasets/1_Vegetation/Existing_Vegetation/1-existing-vegetation-type.qmd
              - href: LANDFIRE_Datasets/1_Vegetation/Existing_Vegetation/2-existing-vegetation-cover.qmd
              - href: LANDFIRE_Datasets/1_Vegetation/Existing_Vegetation/3-existing-vegetation-height.qmd
          - section: "Succession Class"
            contents:
              - href: LANDFIRE_Datasets/1_Vegetation/Succession_Class/1-succession-class.qmd
          - section: "Vegetation Departure"
            contents:
              - href: LANDFIRE_Datasets/1_Vegetation/Vegetation_Departure/1-vegetation-departure.qmd
      - section: "LANDFIRE Fuels Datasets"
        contents:
          - href: LANDFIRE_Datasets/2_Fuels/1_fuels.qmd
      - section: "Ways to get LANDFIRE Data"
        contents:
          - href: Get_Data/1-ways-to-get-data.qmd
          - href: Get_Data/2-LANDFIRE-map-viewer.qmd
          - href: Get_Data/3-full-extent-mosaics.qmd
          - href: Get_Data/4-LANDFIRE-data-streaming.qmd
          - href: Get_Data/5-rlandfire.qmd
    
    
  body-footer: |
    {% include 'footer.html' %}
      

format:
  html:
    theme: 
      light: lumen
      dark: cyborg
    css: styles.css
    toc: false
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 2.25rem

editor: source

